name: SOOS SAST Analysis
 
on: [push]
 
jobs:
  soos_sast_analysis:
    name: SOOS SAST Analysis
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Run SOOS SAST Analysis
      uses: soos-io/soos-sast-github-action@v1
      with:
        client_id: ${{ secrets.SOOS_CLIENT_ID }}
        api_key: ${{ secrets.SOOS_API_KEY }}
        project_name: "Juice Shop Project"
        sast_path: "./juice-shop-master"


# on: [push]

# jobs:
#   soos-sca-analysis:
#     name: SOOS SCA Scan
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - name: Run SOOS - Scan for vulnerabilities
#       uses: soos-io/soos-sca-github-action@v2 # Get Latest Version from https://github.com/marketplace/actions/soos-core-sca
#       with:
#         project_name: "My Project Name"
#         client_id: ${{ secrets.SOOS_CLIENT_ID }}
#         api_key: ${{ secrets.SOOS_API_KEY }}