# on: [push]

# jobs:
#   soos_sast_analysis_example:
#     name: SOOS SAST Analysis Example
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@master
#       - name: Run SOOS SAST Analysis
#         uses: soos-io/soos-sast-github-action@v1 # GET Latest Version from https://github.com/marketplace/actions/soos-sast
#         with:
#           client_id: ${{ secrets.SOOS_CLIENT_ID }}
#           api_key: ${{ secrets.SOOS_API_KEY }}
#           project_name: "My Project Name"
#           sast_path: "./juice-shop-master"
          


on: [push]

jobs:
  soos_sast_analysis_example:
    name: SOOS SAST Analysis Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Change to the previous directory and then select juice-shop-master
      - name: Navigate to juice-shop-master
        run: |
          cd ..
          cd juice-shop-master

      # Example step to generate SARIF files (replace with your actual tool)
      - name: Run ESLint
        run: |
          npm install
          npm run lint -- --format sarif --output-file ./eslint-results.sarif.json

      - name: List SARIF files for debugging
        run: |
          echo "Listing SARIF files in the SAST path:"
          find . -name "*.sarif.json"

      - name: Run SOOS SAST Analysis
        uses: soos-io/soos-sast-github-action@v1 # GET Latest Version from https://github.com/marketplace/actions/soos-sast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "My Project Name"
          sast_path: "."
